### ISSUE TITLE
Investigate slowness when starting the Rails server

### ISSUE THREAD

**Issue by LucianU** [code4romania/scribeAPI#2]
Running `rails s` takes a really long time (>10 seconds). Find out why that is happening and improve performance if possible.

**Comment by LucianU** [comment]
@horiaradu, poți să te uiți la asta?

**Comment by horiaradu** [comment]
Checked and everything works fine, both local setup and vagrant

* Mac OSX Sierra 10.12.3
* vagrant 1.8.4
* virtualbox 5.0.28
